version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/webapp/angelr_app/:rw
    env_file:
      - .env.dev
  admin:
    build: /Users/ismail/Projects/Jobs/angelr/angelr_admin
    command: bundle exec rails s -p 3010 -b '0.0.0.0'
    ports:
      - "3010:3010"
    links:
      - db
    volumes:
      - /Users/ismail/Projects/Jobs/angelr/angelr_admin:/webapp/angelr_admin/:rw
    env_file:
      - .env.dev