default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password:

development:
  <<: *default
  database: angelr_app_development

test:
  <<: *default
  database: angelr_app_test

production:
  <<: *default
  database: angelr_app_production
  username: angelr_app
  password: <%= ENV['ANGELR_APP_DATABASE_PASSWORD'] %>